### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by indigoram89** [eyewitness/eye#18]
<img width="759" alt="2018-03-08 22 40 17" src="https://user-images.githubusercontent.com/10687211/37172421-c654bf42-2321-11e8-99b8-f280f1900351.png">

**Comment by indigoram89** [comment]
I can't open dashboard.

**Comment by laurencei** [comment]
Hi @indigoram89 - I'm sorry about this.

I know the general cause is due to a O(n) vs O+1 issue - but I'm not exactly sure where it is.

Would it be at all possible for you to dump all the "eyewitness_*" tables in your database - and send through to me laurence@eyewitness.io as a zip?

I can then recreate the issue here and send a patch through immediately to fix the problem.

**Comment by indigoram89** [comment]
@laurencei, yes I sent it for you.

**Comment by laurencei** [comment]
@indigoram89 - ok, I've found the issue. If you update to the latest package version - it should work.

**Comment by indigoram89** [comment]
@laurencei thank you, problem is resolved
