### ISSUE TITLE
Log file filled up with Unable to map the Failed Job

### ISSUE THREAD

**Issue by CaptainHypertext** [eyewitness/eye#23]
We've been trying out Eyewitness with our CRM app.  Since putting it up on our staging server, the log file has been filled up with 50 MB of this statement:

`
Eyewitness: Unable to map the Failed Job {"exception":"unserialize() expects parameter 1 to be string, object given","data":null}
`

Any idea what this means?  Is this something perhaps on our end, or eyewitness?  We're running Laravel 5.2 and have several scheduled tasks that run every night.  Any help would be appreciated.

**Comment by laurencei** [comment]
Hi @CaptainHypertext - I've just pushed a commit that will address this.

The most likely cause is a unique payload on the job that we cant decode. The new version will ensure that it doesnt spam your logs, and continues on grarefully. When this occurs - you can still view all details about the payload on Eyewitness - but it'll be the raw data, rather than the nicer looking decoded version.

**Comment by CaptainHypertext** [comment]
@laurencei Much appreciated!
