### ISSUE TITLE
eyewitness:poll job eat all server memory

### ISSUE THREAD

**Issue by edbizarro** [eyewitness/eye#45]
after last commit, my queue keep eating all my server memory with `eyewitness:poll` job

![](https://i.imgur.com/ImANjWc.jpg?1)

Edit: I'm using the `beta` version

**Comment by edbizarro** [comment]
It is worth mentioning that I have about to 15.000 failed jobs with a significant payload each

**Comment by laurencei** [comment]
Do you know how long it was between updates before this occured? i.e. how long before the last update did you do another one? 

I'm trying to track down the cause.

**Comment by laurencei** [comment]
Hi @edbizarro - just touching base. Is this still occuring in the latest beta version of Eyewitness? We've made some small changes - so I'm interested to know if you have any issues still.

Thanks!

**Comment by jzhang917** [comment]
Mine is the lastest eyewitness, and my laravel version is 5.2. Since around September, eyewitness not working anymore. Keep getting execute time over 30s or 60s error and memory exhausted:
![image](https://user-images.githubusercontent.com/30084009/49035606-24248280-f16a-11e8-8894-6117a9527e6f.png)
I have to give execution time 300s to remove the execution time error. But for the memory error, I could not resolve whatever amount i tried. Could you guys give me any idea? Thanks.
